dist: xenial
install:
 - PYTHON_MAJOR=$( python -c 'import sys; print(sys.version_info.major)' )
 - PYTHON_MINOR=$( python -c 'import sys; print(sys.version_info.minor)' )
 - python -m pip install -U pip setuptools
 - pip install -U --force-reinstall -r requirements-ci.txt
 - if (( ( $PYTHON_MAJOR > 3 ) || ( $PYTHON_MAJOR == 3 && $PYTHON_MINOR >= 6 ) )); then pip install -r requirements-flake8.txt; fi
language: python
python:
 - 3.4
 - 3.5
 - 3.6
 - 3.7
 - 3.8-dev
jobs:
 include:
  - os: windows
    language: sh
    python: "3.7"
    before_install:
     - choco install python --version 3.7.2
     - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
     - export PYTHONUNBUFFERED=1
script:
 - python --version
 - pip list
 - pytest
 - if (( $PYTHON_MAJOR == 3 && $PYTHON_MINOR == 7 )); then tox -e flake8; else echo "No flake8."; fi
